CREATE TABLE `inuse_vms` (
	`uuid` VARCHAR(50) NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`ip` VARCHAR(50) NOT NULL,
	`server` VARCHAR(50) NOT NULL,
	`game` VARCHAR(100) NULL DEFAULT NULL,
	PRIMARY KEY (`uuid`)
)